import { account } from "@clearhead/database/schema"
import { eq } from "drizzle-orm"
import { BadgeCheck, CalendarDays, Mail, UserRound } from "lucide-react"
import { DeleteAccountButton } from "@/components/AccountActions"
import { db } from "@/lib/server-db"
import { entitlementForUser } from "@/lib/entitlements"
import { requireSession } from "@/lib/session"

export default async function AccountPage(){const session=await requireSession();const entitlement=await entitlementForUser(session.user.id);const providers=await db.select({provider:account.providerId}).from(account).where(eq(account.userId,session.user.id));const plan=entitlement.plan==="trial"?`Pro trial · ${entitlement.trialDaysRemaining} days remaining`:entitlement.plan==="pro"?`Clearhead Pro${entitlement.billingInterval?` · ${entitlement.billingInterval==="year"?"Annual":"Monthly"}`:""}`:"Clearhead Free";return <div className="space-y-6"><div><p className="eyebrow">Your Clearhead</p><h1 className="mt-4 text-3xl font-semibold tracking-tight text-slate-950">Account</h1></div><div className="web-card"><div className="grid gap-5 sm:grid-cols-2"><Detail icon={UserRound} label="Name" value={session.user.name}/><Detail icon={Mail} label="Email" value={session.user.email}/><Detail icon={BadgeCheck} label="Account security" value={session.user.emailVerified?"Email verified":"Verification required"}/><Detail icon={CalendarDays} label="Plan" value={plan}/></div></div><div className="web-card"><h2 className="font-semibold text-slate-950">Ways to sign in</h2><p className="mt-2 text-sm text-slate-500">{providers.map(item=>item.provider==="credential"?"Email and password":item.provider).join(" · ")||"Email and password"}</p></div><div className="rounded-3xl border border-red-200 bg-red-50/60 p-6"><h2 className="font-semibold text-red-800">Delete account</h2><p className="mb-5 mt-2 text-sm text-slate-600">This permanently removes your cloud account. Data saved locally in the extension stays on your device.</p><DeleteAccountButton/></div></div>}
function Detail({icon:Icon,label,value}:{icon:typeof UserRound;label:string;value:string}){return <div className="flex gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><Icon className="mt-0.5 size-5 text-indigo-600"/><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-medium text-slate-900">{value}</p></div></div>}
